### PR TITLE
Add better video skipping

### PR DESCRIPTION
**Pull request by wearrrrr**
You're welcome

### CODE REVIEW

**Comment by smorenitez** [comment]
I dont know what this code does. What does it do.

**Comment by genericness** [comment]
don't add a rickroll + don't obfuscate your code

```
window.location.href = "https://www.youtube.com/watch?v=PXqcHi2fkXI";
```

**Comment by wearrrrr** [comment]
> don't add a troll video + don't obfuscate your code
> 
> ```
> window.location.href = "https://www.youtube.com/watch?v=PXqcHi2fkXI";
> ```

what?

**Comment by genericness** [comment]
> > don't add a troll video + don't obfuscate your code
> > ```
> > window.location.href = "https://www.youtube.com/watch?v=PXqcHi2fkXI";
> > ```
> 
> what?

it opens a troll video lol

**Comment by wearrrrr** [comment]
no lol

**Pull request closed without merging**
